package com.simra.konsumgandalf.common.models.entities;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import org.locationtech.jts.geom.Geometry;

import java.util.List;

/**
 * Contains multiple regions to a super region.
 */
@Entity
public class SimraRegion {

	@Id
	@Column
	private String name;

	@OneToMany(cascade = CascadeType.ALL, mappedBy = "region")
	@JsonBackReference
	private List<SafetyMetricsSimraRegion> safetyMetricsSimraRegions;

	@ManyToMany(cascade = CascadeType.ALL)
	@JoinTable(name = "simra_region_region",
			joinColumns = @JoinColumn(name = "simra_region_name", referencedColumnName = "name"),
			inverseJoinColumns = @JoinColumn(name = "region_name", referencedColumnName = "name"))
	private List<Region> regions;

	@Column
	private Float avgSegmentDistance;

	/**
	 * Automatically generated by a trigger in the database.
	 */
	@Column
	Geometry way;

	public SimraRegion() {
	}

	public SimraRegion(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<Region> getRegions() {
		return regions;
	}

	public void setRegions(List<Region> regions) {
		this.regions = regions;
	}

	public List<SafetyMetricsSimraRegion> getSafetyMetricsSimraRegions() {
		return safetyMetricsSimraRegions;
	}

	public void setSafetyMetricsSimraRegions(List<SafetyMetricsSimraRegion> safetyMetricsSimraRegions) {
		this.safetyMetricsSimraRegions = safetyMetricsSimraRegions;
	}

	public Geometry getWay() {
		return way;
	}

	public void setWay(Geometry way) {
		this.way = way;
	}

	public Float getAvgSegmentDistance() {
		return avgSegmentDistance;
	}

	public void setAvgSegmentDistance(Float avgSegmentDistance) {
		this.avgSegmentDistance = avgSegmentDistance;
	}

}
