server:
  port: ${SIMRA_PORT:8080}
  servlet:
    context-path: /api

spring:
  codec:
    max-in-memory-size: 10MB
  config:
    import: optional:file:.env[.properties]
  application:
    name: backend
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGIS_DB_HOST}
    username: ${POSTGIS_DB_USER}
    password: ${POSTGIS_DB_PASSWORD}
    hikari:
      maximum-pool-size: 32
      minimum-idle: 2
      connection-timeout: 600000

  jpa:
    hibernate:
      ddl-auto: update # not delete existing columns which is important for the osm tables
      show-sql: true
      database: postgresql
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always


management:
  endpoints:
    web:
      exposure:
        include: "*"
# logging:
 #  level:
 #   ROOT: DEBUG
#        org.springframework.web.reactive.function.client.WebClientResponseException: OFF
#        reactor.core.publisher: OFF
