server:
  port: ${SIMRA_PORT:8080}
  servlet:
    context-path: /api

spring:
  codec:
    max-in-memory-size: 10MB
  config:
    import: optional:file:.env[.properties]
  application:
    name: backend
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGIS_DB_HOST}
    username: ${POSTGIS_DB_USER}
    password: ${POSTGIS_DB_PASSWORD}
    hikari:
      maximum-pool-size: 32
      minimum-idle: 2
      connection-timeout: 600000

  jpa:
    hibernate:
      ddl-auto: update # not delete existing columns which is important for the osm tables
      show-sql: true
      database: postgresql
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 100
          batch_versioned_data: true
        order_updates: true
        order_inserts: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always


management:
  endpoint:
    health:
      show-details: always
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
