@startuml
actor "User" as User
actor App

node "Docker Host" as DockerHost {
    frame "Containerized Environment" {

        node "Apache Server Webserver" as Dashboard {
            [Dashboard (HTML/TypeScript)]
        }
        database "Colored Shapes Data" as OSMColoredShapes
        database "Shapes Data" as OSMShapes
        database "CSV Files" as CSV

        node "Processing Container " as OSMAggregator {
            [OSM Aggregator]
        }

        node "Processing Container Coloring" as OSMColoring {
            [OSM Coloring]
        }

        node "Backend Container" as Backend {
            [SimRa Backend]
        }
    }
}

note "Is runnning as Linux Cron Job" as cron_note
cron_note -down-> OSMAggregator
cron_note -down-> OSMColoring

App -down-> Backend: Send the newest ride date
Backend -down-> CSV: Creates new rides
CSV -down-> OSMAggregator: Read Rides, aggregating them
OSMAggregator --> OSMShapes
OSMShapes --> OSMColoring: Read Shapes, coloring them
OSMColoring -up-> OSMColoredShapes

OSMColoredShapes -up-> Dashboard
User -down-> Dashboard: See Map

@enduml
