@startuml
start

:Start analysis of OSM highway metrics;

repeat
    :Fetch next page of street segments;

    :Asynchronously process current page;

    if (Pool size reached?) then (yes)
        :Wait for current batch to complete;
    endif
repeat while (More pages available?)

:For each street segment:
:Calculate safety metrics per traffic time, d

#####x+ay and year;
:Add incident data to safety metrics;
:Calculate dangerousness scores & color;

:Aggregate values per year, week and day combinations;
:Save all safety metrics to database;
:Update last analysed timestamps for streets;

stop
@enduml
