server:
    port: 8081

spring:
    config:
        import: optional:file:.env[.properties]
    application:
        name: backend
    devtools:
      restart:
          enabled: true
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${POSTGIS_DB_HOST}
        username: ${POSTGIS_DB_USER}
        password: ${POSTGIS_DB_PASSWORD}