name: CI
on: push

env:
  JAVA_VERSION: 23
  JAVA_DISTRIBUTION: 'oracle'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Formatting
        run: ./gradlew format
      - name: Test formatting
        run: ./gradlew formatMain
      - name: Main formatting
        run: ./gradlew formatTest
      - name: Test
        run: ./gradlew test
      - name: Build
        run: ./gradlew build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/libs
