name: CI
on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'oracle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - uses: actions/checkout@v4
      - name: Lint
        run: ./gradlew format

  format:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: ./gradlew format

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: ./gradlew test

  build:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: ./gradlew build
