name: Publish Artifact
on:
  push:
    branches:
      - main

env:
  JAVA_VERSION: 23
  JAVA_DISTRIBUTION: 'oracle'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.ref_name }}
          path: build/libs
