name: Publish Artifact

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

env:
  JAVA_VERSION: 23
  JAVA_DISTRIBUTION: 'oracle'

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build
      - name: Publish Artifact
        id: publish-artifact
        uses: actions/upload-artifact@v4
        with:
          name: simra-${{ github.sha }}
          path: build/libs
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: java
          target-branch: main
