name: Publish Release

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    name: Build and Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')

      - uses: googleapis/release-please-action@v4
        with:
          release-type: java
          target-branch: ${{ github.ref_name }}
