name: Upload Artifact

on:
  push:
    branches:
    - main
    - develop

permissions:
  packages: write

env:
  JAVA_VERSION: 23
  JAVA_DISTRIBUTION: 'oracle'

jobs:
  upload:
    name: Upload Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build
      - name: Publish Artifact
        id: publish-artifact
        uses: actions/upload-artifact@v4
        with:
          name: simra-${{ github.sha }}
          path: build/libs
      - name: Fetch latest release version
        id: fetch-latest-release
        uses: reloc8/action-latest-release-version@1.0.0
      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.fetch-latest-release.outputs.latest-release }} build/libs/*.jar
